[package]
name = "bench-warm-container-minimum"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "bench_warm_container_minimum"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bench-warm-container-shared = { path = "../warm-container-shared" }
mockspace-bench-core = { git = "ssh://git@github.com/hiisi-digital/mockspace.git", branch = "dev", features = ["std"] }
mockspace-bench-macro = { git = "ssh://git@github.com/hiisi-digital/mockspace.git", branch = "dev" }
