[package]
name = "bench-bitpack-contend-pipe2"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "bench_bitpack_contend_pipe2"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
mockspace-bench-core = { git = "ssh://git@github.com/hiisi-digital/mockspace.git", branch = "dev", features = ["std"] }
mockspace-bench-macro = { git = "ssh://git@github.com/hiisi-digital/mockspace.git", branch = "dev" }
bench-bitpack-contend-shared = { path = "../bitpack-contend-shared" }
